{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deno-web-app.fullname" . }}-secret
  labels:
    {{- include "deno-web-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
