apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: deno-web-app
  labels:
    app: tempo
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
      log_level: info
      
    distributor:
      receivers:
        jaeger:
          protocols:
            thrift_compact:
              endpoint: 0.0.0.0:6831
            thrift_binary:
              endpoint: 0.0.0.0:6832
            grpc:
              endpoint: 0.0.0.0:14250
        zipkin:
          endpoint: 0.0.0.0:9411
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
        opencensus:
          endpoint: 0.0.0.0:55678
          
    ingester:
      max_block_duration: 5m               
      
    compactor:
      compaction:
        block_retention: 1h               

    metrics_generator:
      registry:
        external_labels:
          source: tempo
          cluster: docker-compose
      storage:
        path: /tmp/tempo/generator/wal
        remote_write:
          - url: http://prometheus:9090/api/v1/write
            send_exemplars: true

    storage:
      trace:
        backend: local                     
        wal:
          path: /tmp/tempo/wal             
        local:
          path: /tmp/tempo/blocks
        pool:
          max_workers: 100                 
          queue_depth: 10000

    querier:
      max_concurrent_queries: 10
      
    query_frontend:
      search:
        duration_slo: 5s
        throughput_bytes_slo: 1.073741824e+09
      trace_by_id:
        duration_slo: 5s

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-pvc
  namespace: deno-web-app
  labels:
    app: tempo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: standard-rwo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: deno-web-app
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      serviceAccountName: tempo
      containers:
        - name: tempo
          image: grafana/tempo:2.2.0
          args:
            - "-config.file=/etc/tempo.yaml"
          ports:
            - containerPort: 3200
              name: tempo
            - containerPort: 6831
              name: jaeger-thrift-c
              protocol: UDP
            - containerPort: 6832
              name: jaeger-thrift-b
              protocol: UDP
            - containerPort: 14250
              name: jaeger-grpc
            - containerPort: 9411
              name: zipkin
            - containerPort: 55678
              name: opencensus
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo.yaml
              subPath: tempo.yaml
            - name: tempo-storage
              mountPath: /tmp/tempo
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /ready
              port: tempo
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /ready
              port: tempo
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
        - name: tempo-storage
          persistentVolumeClaim:
            claimName: tempo-pvc

---
# Tempo Service
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: deno-web-app
  labels:
    app: tempo
spec:
  ports:
    - port: 3200
      protocol: TCP
      targetPort: tempo
      name: tempo
    - port: 6831
      protocol: UDP
      targetPort: 6831
      name: jaeger-thrift-compact
    - port: 6832
      protocol: UDP
      targetPort: 6832
      name: jaeger-thrift-binary
    - port: 14250
      protocol: TCP
      targetPort: 14250
      name: jaeger-grpc
    - port: 9411
      protocol: TCP
      targetPort: 9411
      name: zipkin
    - port: 55678
      protocol: TCP
      targetPort: 55678
      name: opencensus
    - port: 4317
      protocol: TCP
      targetPort: 4317
      name: otlp-grpc
    - port: 4318
      protocol: TCP
      targetPort: 4318
      name: otlp-http
  selector:
    app: tempo
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: deno-web-app
  labels:
    app: otel-collector
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      jaeger:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14250
          thrift_http:
            endpoint: 0.0.0.0:14268
          thrift_compact:
            endpoint: 0.0.0.0:6831
          thrift_binary:
            endpoint: 0.0.0.0:6832
      zipkin:
        endpoint: 0.0.0.0:9411

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
      resource:
        attributes:
          - key: service.namespace
            value: deno-web-app
            action: upsert

    exporters:
      otlp:
        endpoint: tempo.deno-web-app.svc.cluster.local:4317
        tls:
          insecure: true

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      pprof:
        endpoint: 0.0.0.0:1777
      zpages:
        endpoint: 0.0.0.0:55679

    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [otlp, jaeger, zipkin]
          processors: [batch, resource]
          exporters: [otlp]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: deno-web-app
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      serviceAccountName: otel-collector
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.88.0
          args:
            - --config=/conf/otel-collector-config.yaml
          ports:
            - containerPort: 1777   # pprof extension
            - containerPort: 4317   # OTLP gRPC receiver
            - containerPort: 4318   # OTLP HTTP receiver
            - containerPort: 6831   # Jaeger thrift compact
            - containerPort: 6832   # Jaeger thrift binary
            - containerPort: 8888   # Prometheus metrics
            - containerPort: 8889   # Prometheus exporter metrics
            - containerPort: 9411   # Zipkin
            - containerPort: 13133  # health_check extension
            - containerPort: 14250  # Jaeger gRPC
            - containerPort: 14268  # Jaeger thrift HTTP
            - containerPort: 55679  # zpages extension
          volumeMounts:
            - name: otel-collector-config-vol
              mountPath: /conf
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: otel-collector-config-vol
          configMap:
            name: otel-collector-config

---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: deno-web-app
  labels:
    app: otel-collector
spec:
  ports:
    - name: otlp-grpc
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: otlp-http
      port: 4318
      protocol: TCP
      targetPort: 4318
    - name: jaeger-grpc
      port: 14250
      protocol: TCP
      targetPort: 14250
    - name: jaeger-thrift-http
      port: 14268
      protocol: TCP
      targetPort: 14268
    - name: jaeger-thrift-compact
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: jaeger-thrift-binary
      port: 6832
      protocol: UDP
      targetPort: 6832
    - name: zipkin
      port: 9411
      protocol: TCP
      targetPort: 9411
    - name: metrics
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: otel-collector
  type: ClusterIP

---
# Tempo ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tempo
  namespace: deno-web-app
  labels:
    app: tempo

---
# OpenTelemetry Collector ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: deno-web-app
  labels:
    app: otel-collector
