# Helm Chart 默認配置值

# 全域設定
replicaCount: 2
nameOverride: ""
fullnameOverride: ""

# 映像配置
image:
  repository: ghcr.io/tkuim-111-is/web
  pullPolicy: Always
  tag: "latest"

# 映像拉取密鑰
imagePullSecrets:
  - name: ghcr-auth

# 服務帳戶
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod 安全內容
podSecurityContext: {}

# 安全內容
securityContext: {}

# 服務配置
service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

# Ingress 配置
ingress:
  enabled: true
  className: "gce"
  annotations: {}
    # kubernetes.io/ingress.global-static-ip-name: "web-static-ip"
    # networking.gke.io/managed-certificates: "web-cert"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

# 資源限制
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

# 自動擴展
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Node 選擇器
nodeSelector: {}

# 容忍度
tolerations: []

# 親和性
affinity: {}

# 健康檢查
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# 環境變數 (ConfigMap)
config:
  PORT: "8000"
  HOST: "0.0.0.0"
  DB_HOST: "localhost"
  DB_NAME: "is_db"
  DB_PORT: "3306"
  OTEL_COLLECTOR_URL: "http://localhost:4318"
  SERVICE_NAME: "deno-web-app"
  SERVICE_VERSION: "1.0.0"
  ENVIRONMENT: "development"

# 機密變數 (Secret) - 這些應該在部署時提供
secrets: {}
  # DB_PASSWORD: ""
  # JWT_SECRET: ""
