name: Deploy (develop -> server via rsync)

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: [self-hosted, linux, X64]
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Get Vault Token and SSH Certificate
      id: vault-ssh
      run: |
        export VAULT_TOKEN=$(vault write -format=json auth/approle/login \
          role_id=${{ secrets.VAULT_ROLE_ID }} \
          secret_id=${{ secrets.VAULT_SECRET_ID }} | jq -r '.auth.client_token')
        
        vault write -format=json ssh/creds/deployer-role \
          public_key=@/home/runner/.ssh/id_rsa.pub \
          > signed_key.json
          
        jq -r '.data.signed_key' signed_key.json > id_rsa-cert.pub

    - name: Set up SSH Key and Certificate
      run: |
        eval $(ssh-agent -s)
        
        echo "${{ secrets.SSH_KEY }}" | ssh-add -
        ssh-add id_rsa-cert.pub

    - name: Sync code to server with rsync
      run: |
        rsync -avz \
          --delete \
          -e "ssh -o StrictHostKeyChecking=no" \
          --exclude='.git/' \
          --exclude='.github/' \
          --exclude='node_modules/' \
          --exclude='tests/' \
          --exclude='.env' \
          --exclude='logs/' \
          ./ deployer@${{ secrets.SSH_HOST }}:/home/deployer/web/

    - name: Restart service via SSH
      run: |
        ssh deployer@${{ secrets.SSH_HOST }} "bash /home/deployer/web/deploy.sh"