name: Runner Test
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  smoke:
    runs-on: [self-hosted, linux, x64, deploy]
    steps:
      - name: Show runner info
        run: |
          whoami
          uname -a
          ls -la
      - name: Check Vault CLI (optional)
        run: |
          command -v vault && vault version || echo "Vault CLI not preinstalled on runner"
